/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"
#import "TAsyncTransport.h"
#import "TProtocolFactory.h"
#import "TBaseClient.h"


enum Gender {
  Gender_male = 0,
  Gender_female = 1
};

@interface Response : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  NSString * __msg;
  NSString * __data;

  BOOL __errorCode_isset;
  BOOL __msg_isset;
  BOOL __data_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=msg, setter=setMsg:) NSString * msg;
@property (nonatomic, retain, getter=data, setter=setData:) NSString * data;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode msg: (NSString *) msg data: (NSString *) data;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) msg;
- (void) setMsg: (NSString *) msg;
#endif
- (BOOL) msgIsSet;

#if !__has_feature(objc_arc)
- (NSString *) data;
- (void) setData: (NSString *) data;
#endif
- (BOOL) dataIsSet;

@end

@interface ResponseDouble : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  NSString * __msg;
  double __data;

  BOOL __errorCode_isset;
  BOOL __msg_isset;
  BOOL __data_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=msg, setter=setMsg:) NSString * msg;
@property (nonatomic, getter=data, setter=setData:) double data;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode msg: (NSString *) msg data: (double) data;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) msg;
- (void) setMsg: (NSString *) msg;
#endif
- (BOOL) msgIsSet;

#if !__has_feature(objc_arc)
- (double) data;
- (void) setData: (double) data;
#endif
- (BOOL) dataIsSet;

@end

@interface Auth : NSObject <TBase, NSCoding> {
  NSString * __AppId;
  NSString * __AppSecret;
  NSString * __accessToken;
  int64_t __uid;

  BOOL __AppId_isset;
  BOOL __AppSecret_isset;
  BOOL __accessToken_isset;
  BOOL __uid_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=appId, setter=setAppId:) NSString * AppId;
@property (nonatomic, retain, getter=appSecret, setter=setAppSecret:) NSString * AppSecret;
@property (nonatomic, retain, getter=accessToken, setter=setAccessToken:) NSString * accessToken;
@property (nonatomic, getter=uid, setter=setUid:) int64_t uid;
#endif

- (id) init;
- (id) initWithAppId: (NSString *) AppId AppSecret: (NSString *) AppSecret accessToken: (NSString *) accessToken uid: (int64_t) uid;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) appId;
- (void) setAppId: (NSString *) AppId;
#endif
- (BOOL) AppIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) appSecret;
- (void) setAppSecret: (NSString *) AppSecret;
#endif
- (BOOL) AppSecretIsSet;

#if !__has_feature(objc_arc)
- (NSString *) accessToken;
- (void) setAccessToken: (NSString *) accessToken;
#endif
- (BOOL) accessTokenIsSet;

#if !__has_feature(objc_arc)
- (int64_t) uid;
- (void) setUid: (int64_t) uid;
#endif
- (BOOL) uidIsSet;

@end

@interface ResponseAuth : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  NSString * __msg;
  Auth * __data;

  BOOL __errorCode_isset;
  BOOL __msg_isset;
  BOOL __data_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=msg, setter=setMsg:) NSString * msg;
@property (nonatomic, retain, getter=data, setter=setData:) Auth * data;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode msg: (NSString *) msg data: (Auth *) data;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) msg;
- (void) setMsg: (NSString *) msg;
#endif
- (BOOL) msgIsSet;

#if !__has_feature(objc_arc)
- (Auth *) data;
- (void) setData: (Auth *) data;
#endif
- (BOOL) dataIsSet;

@end

@interface InvalidOperation : NSException <TBase, NSCoding> {
  int32_t __whatOp;
  NSString * __why;

  BOOL __whatOp_isset;
  BOOL __why_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=whatOp, setter=setWhatOp:) int32_t whatOp;
@property (nonatomic, retain, getter=why, setter=setWhy:) NSString * why;
#endif

- (id) init;
- (id) initWithWhatOp: (int32_t) whatOp why: (NSString *) why;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) whatOp;
- (void) setWhatOp: (int32_t) whatOp;
#endif
- (BOOL) whatOpIsSet;

#if !__has_feature(objc_arc)
- (NSString *) why;
- (void) setWhy: (NSString *) why;
#endif
- (BOOL) whyIsSet;

@end

@interface Order : NSObject <TBase, NSCoding> {
  int64_t __orderId;
  int64_t __customerId;
  NSString * __mobilePhone;
  NSString * __userCalled;
  NSString * __address;
  int64_t __servicePriceId;
  NSString * __sourceId;
  NSString * __provinceName;
  NSString * __provinceCode;
  NSString * __cityName;
  int32_t __cityCode;
  int32_t __storeId;
  int64_t __psrId;
  uint8_t __status;
  uint8_t __camera;
  NSString * __doorTime;
  NSString * __contractTime;
  NSString * __startTime;
  NSString * __endTime;
  double __totalFeeOrigin;
  double __totalFee;
  NSString * __photoBefore;
  NSString * __photoInProgress;
  NSString * __photoAfter;
  NSString * __pauseReasonMemo;
  NSString * __remark;
  NSString * __createTime;
  NSString * __modifyTime;
  NSString * __statusName;
  NSString * __revServiceName;
  NSString * __psrServiceMemo;
  NSString * __cscAssignsOrderMemo;
  NSString * __psrStopOrderMemo;
  NSString * __psrDoorMemo;
  NSString * __sourceName;
  NSString * __sourceIcon;
  NSString * __foremanId;
  NSString * __foremanName;
  NSString * __isDistribute;
  NSString * __doorTimeShow;
  NSString * __activitiesName;
  NSString * __workerName;
  uint8_t __cameraIsBack;
  NSString * __cameraCode;

  BOOL __orderId_isset;
  BOOL __customerId_isset;
  BOOL __mobilePhone_isset;
  BOOL __userCalled_isset;
  BOOL __address_isset;
  BOOL __servicePriceId_isset;
  BOOL __sourceId_isset;
  BOOL __provinceName_isset;
  BOOL __provinceCode_isset;
  BOOL __cityName_isset;
  BOOL __cityCode_isset;
  BOOL __storeId_isset;
  BOOL __psrId_isset;
  BOOL __status_isset;
  BOOL __camera_isset;
  BOOL __doorTime_isset;
  BOOL __contractTime_isset;
  BOOL __startTime_isset;
  BOOL __endTime_isset;
  BOOL __totalFeeOrigin_isset;
  BOOL __totalFee_isset;
  BOOL __photoBefore_isset;
  BOOL __photoInProgress_isset;
  BOOL __photoAfter_isset;
  BOOL __pauseReasonMemo_isset;
  BOOL __remark_isset;
  BOOL __createTime_isset;
  BOOL __modifyTime_isset;
  BOOL __statusName_isset;
  BOOL __revServiceName_isset;
  BOOL __psrServiceMemo_isset;
  BOOL __cscAssignsOrderMemo_isset;
  BOOL __psrStopOrderMemo_isset;
  BOOL __psrDoorMemo_isset;
  BOOL __sourceName_isset;
  BOOL __sourceIcon_isset;
  BOOL __foremanId_isset;
  BOOL __foremanName_isset;
  BOOL __isDistribute_isset;
  BOOL __doorTimeShow_isset;
  BOOL __activitiesName_isset;
  BOOL __workerName_isset;
  BOOL __cameraIsBack_isset;
  BOOL __cameraCode_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=orderId, setter=setOrderId:) int64_t orderId;
@property (nonatomic, getter=customerId, setter=setCustomerId:) int64_t customerId;
@property (nonatomic, retain, getter=mobilePhone, setter=setMobilePhone:) NSString * mobilePhone;
@property (nonatomic, retain, getter=userCalled, setter=setUserCalled:) NSString * userCalled;
@property (nonatomic, retain, getter=address, setter=setAddress:) NSString * address;
@property (nonatomic, getter=servicePriceId, setter=setServicePriceId:) int64_t servicePriceId;
@property (nonatomic, retain, getter=sourceId, setter=setSourceId:) NSString * sourceId;
@property (nonatomic, retain, getter=provinceName, setter=setProvinceName:) NSString * provinceName;
@property (nonatomic, retain, getter=provinceCode, setter=setProvinceCode:) NSString * provinceCode;
@property (nonatomic, retain, getter=cityName, setter=setCityName:) NSString * cityName;
@property (nonatomic, getter=cityCode, setter=setCityCode:) int32_t cityCode;
@property (nonatomic, getter=storeId, setter=setStoreId:) int32_t storeId;
@property (nonatomic, getter=psrId, setter=setPsrId:) int64_t psrId;
@property (nonatomic, getter=status, setter=setStatus:) uint8_t status;
@property (nonatomic, getter=camera, setter=setCamera:) uint8_t camera;
@property (nonatomic, retain, getter=doorTime, setter=setDoorTime:) NSString * doorTime;
@property (nonatomic, retain, getter=contractTime, setter=setContractTime:) NSString * contractTime;
@property (nonatomic, retain, getter=startTime, setter=setStartTime:) NSString * startTime;
@property (nonatomic, retain, getter=endTime, setter=setEndTime:) NSString * endTime;
@property (nonatomic, getter=totalFeeOrigin, setter=setTotalFeeOrigin:) double totalFeeOrigin;
@property (nonatomic, getter=totalFee, setter=setTotalFee:) double totalFee;
@property (nonatomic, retain, getter=photoBefore, setter=setPhotoBefore:) NSString * photoBefore;
@property (nonatomic, retain, getter=photoInProgress, setter=setPhotoInProgress:) NSString * photoInProgress;
@property (nonatomic, retain, getter=photoAfter, setter=setPhotoAfter:) NSString * photoAfter;
@property (nonatomic, retain, getter=pauseReasonMemo, setter=setPauseReasonMemo:) NSString * pauseReasonMemo;
@property (nonatomic, retain, getter=remark, setter=setRemark:) NSString * remark;
@property (nonatomic, retain, getter=createTime, setter=setCreateTime:) NSString * createTime;
@property (nonatomic, retain, getter=modifyTime, setter=setModifyTime:) NSString * modifyTime;
@property (nonatomic, retain, getter=statusName, setter=setStatusName:) NSString * statusName;
@property (nonatomic, retain, getter=revServiceName, setter=setRevServiceName:) NSString * revServiceName;
@property (nonatomic, retain, getter=psrServiceMemo, setter=setPsrServiceMemo:) NSString * psrServiceMemo;
@property (nonatomic, retain, getter=cscAssignsOrderMemo, setter=setCscAssignsOrderMemo:) NSString * cscAssignsOrderMemo;
@property (nonatomic, retain, getter=psrStopOrderMemo, setter=setPsrStopOrderMemo:) NSString * psrStopOrderMemo;
@property (nonatomic, retain, getter=psrDoorMemo, setter=setPsrDoorMemo:) NSString * psrDoorMemo;
@property (nonatomic, retain, getter=sourceName, setter=setSourceName:) NSString * sourceName;
@property (nonatomic, retain, getter=sourceIcon, setter=setSourceIcon:) NSString * sourceIcon;
@property (nonatomic, retain, getter=foremanId, setter=setForemanId:) NSString * foremanId;
@property (nonatomic, retain, getter=foremanName, setter=setForemanName:) NSString * foremanName;
@property (nonatomic, retain, getter=isDistribute, setter=setIsDistribute:) NSString * isDistribute;
@property (nonatomic, retain, getter=doorTimeShow, setter=setDoorTimeShow:) NSString * doorTimeShow;
@property (nonatomic, retain, getter=activitiesName, setter=setActivitiesName:) NSString * activitiesName;
@property (nonatomic, retain, getter=workerName, setter=setWorkerName:) NSString * workerName;
@property (nonatomic, getter=cameraIsBack, setter=setCameraIsBack:) uint8_t cameraIsBack;
@property (nonatomic, retain, getter=cameraCode, setter=setCameraCode:) NSString * cameraCode;
#endif

- (id) init;
- (id) initWithOrderId: (int64_t) orderId customerId: (int64_t) customerId mobilePhone: (NSString *) mobilePhone userCalled: (NSString *) userCalled address: (NSString *) address servicePriceId: (int64_t) servicePriceId sourceId: (NSString *) sourceId provinceName: (NSString *) provinceName provinceCode: (NSString *) provinceCode cityName: (NSString *) cityName cityCode: (int32_t) cityCode storeId: (int32_t) storeId psrId: (int64_t) psrId status: (uint8_t) status camera: (uint8_t) camera doorTime: (NSString *) doorTime contractTime: (NSString *) contractTime startTime: (NSString *) startTime endTime: (NSString *) endTime totalFeeOrigin: (double) totalFeeOrigin totalFee: (double) totalFee photoBefore: (NSString *) photoBefore photoInProgress: (NSString *) photoInProgress photoAfter: (NSString *) photoAfter pauseReasonMemo: (NSString *) pauseReasonMemo remark: (NSString *) remark createTime: (NSString *) createTime modifyTime: (NSString *) modifyTime statusName: (NSString *) statusName revServiceName: (NSString *) revServiceName psrServiceMemo: (NSString *) psrServiceMemo cscAssignsOrderMemo: (NSString *) cscAssignsOrderMemo psrStopOrderMemo: (NSString *) psrStopOrderMemo psrDoorMemo: (NSString *) psrDoorMemo sourceName: (NSString *) sourceName sourceIcon: (NSString *) sourceIcon foremanId: (NSString *) foremanId foremanName: (NSString *) foremanName isDistribute: (NSString *) isDistribute doorTimeShow: (NSString *) doorTimeShow activitiesName: (NSString *) activitiesName workerName: (NSString *) workerName cameraIsBack: (uint8_t) cameraIsBack cameraCode: (NSString *) cameraCode;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) orderId;
- (void) setOrderId: (int64_t) orderId;
#endif
- (BOOL) orderIdIsSet;

#if !__has_feature(objc_arc)
- (int64_t) customerId;
- (void) setCustomerId: (int64_t) customerId;
#endif
- (BOOL) customerIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) mobilePhone;
- (void) setMobilePhone: (NSString *) mobilePhone;
#endif
- (BOOL) mobilePhoneIsSet;

#if !__has_feature(objc_arc)
- (NSString *) userCalled;
- (void) setUserCalled: (NSString *) userCalled;
#endif
- (BOOL) userCalledIsSet;

#if !__has_feature(objc_arc)
- (NSString *) address;
- (void) setAddress: (NSString *) address;
#endif
- (BOOL) addressIsSet;

#if !__has_feature(objc_arc)
- (int64_t) servicePriceId;
- (void) setServicePriceId: (int64_t) servicePriceId;
#endif
- (BOOL) servicePriceIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) sourceId;
- (void) setSourceId: (NSString *) sourceId;
#endif
- (BOOL) sourceIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) provinceName;
- (void) setProvinceName: (NSString *) provinceName;
#endif
- (BOOL) provinceNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) provinceCode;
- (void) setProvinceCode: (NSString *) provinceCode;
#endif
- (BOOL) provinceCodeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) cityName;
- (void) setCityName: (NSString *) cityName;
#endif
- (BOOL) cityNameIsSet;

#if !__has_feature(objc_arc)
- (int32_t) cityCode;
- (void) setCityCode: (int32_t) cityCode;
#endif
- (BOOL) cityCodeIsSet;

#if !__has_feature(objc_arc)
- (int32_t) storeId;
- (void) setStoreId: (int32_t) storeId;
#endif
- (BOOL) storeIdIsSet;

#if !__has_feature(objc_arc)
- (int64_t) psrId;
- (void) setPsrId: (int64_t) psrId;
#endif
- (BOOL) psrIdIsSet;

#if !__has_feature(objc_arc)
- (uint8_t) status;
- (void) setStatus: (uint8_t) status;
#endif
- (BOOL) statusIsSet;

#if !__has_feature(objc_arc)
- (uint8_t) camera;
- (void) setCamera: (uint8_t) camera;
#endif
- (BOOL) cameraIsSet;

#if !__has_feature(objc_arc)
- (NSString *) doorTime;
- (void) setDoorTime: (NSString *) doorTime;
#endif
- (BOOL) doorTimeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) contractTime;
- (void) setContractTime: (NSString *) contractTime;
#endif
- (BOOL) contractTimeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) startTime;
- (void) setStartTime: (NSString *) startTime;
#endif
- (BOOL) startTimeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) endTime;
- (void) setEndTime: (NSString *) endTime;
#endif
- (BOOL) endTimeIsSet;

#if !__has_feature(objc_arc)
- (double) totalFeeOrigin;
- (void) setTotalFeeOrigin: (double) totalFeeOrigin;
#endif
- (BOOL) totalFeeOriginIsSet;

#if !__has_feature(objc_arc)
- (double) totalFee;
- (void) setTotalFee: (double) totalFee;
#endif
- (BOOL) totalFeeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) photoBefore;
- (void) setPhotoBefore: (NSString *) photoBefore;
#endif
- (BOOL) photoBeforeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) photoInProgress;
- (void) setPhotoInProgress: (NSString *) photoInProgress;
#endif
- (BOOL) photoInProgressIsSet;

#if !__has_feature(objc_arc)
- (NSString *) photoAfter;
- (void) setPhotoAfter: (NSString *) photoAfter;
#endif
- (BOOL) photoAfterIsSet;

#if !__has_feature(objc_arc)
- (NSString *) pauseReasonMemo;
- (void) setPauseReasonMemo: (NSString *) pauseReasonMemo;
#endif
- (BOOL) pauseReasonMemoIsSet;

#if !__has_feature(objc_arc)
- (NSString *) remark;
- (void) setRemark: (NSString *) remark;
#endif
- (BOOL) remarkIsSet;

#if !__has_feature(objc_arc)
- (NSString *) createTime;
- (void) setCreateTime: (NSString *) createTime;
#endif
- (BOOL) createTimeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) modifyTime;
- (void) setModifyTime: (NSString *) modifyTime;
#endif
- (BOOL) modifyTimeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) statusName;
- (void) setStatusName: (NSString *) statusName;
#endif
- (BOOL) statusNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) revServiceName;
- (void) setRevServiceName: (NSString *) revServiceName;
#endif
- (BOOL) revServiceNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) psrServiceMemo;
- (void) setPsrServiceMemo: (NSString *) psrServiceMemo;
#endif
- (BOOL) psrServiceMemoIsSet;

#if !__has_feature(objc_arc)
- (NSString *) cscAssignsOrderMemo;
- (void) setCscAssignsOrderMemo: (NSString *) cscAssignsOrderMemo;
#endif
- (BOOL) cscAssignsOrderMemoIsSet;

#if !__has_feature(objc_arc)
- (NSString *) psrStopOrderMemo;
- (void) setPsrStopOrderMemo: (NSString *) psrStopOrderMemo;
#endif
- (BOOL) psrStopOrderMemoIsSet;

#if !__has_feature(objc_arc)
- (NSString *) psrDoorMemo;
- (void) setPsrDoorMemo: (NSString *) psrDoorMemo;
#endif
- (BOOL) psrDoorMemoIsSet;

#if !__has_feature(objc_arc)
- (NSString *) sourceName;
- (void) setSourceName: (NSString *) sourceName;
#endif
- (BOOL) sourceNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) sourceIcon;
- (void) setSourceIcon: (NSString *) sourceIcon;
#endif
- (BOOL) sourceIconIsSet;

#if !__has_feature(objc_arc)
- (NSString *) foremanId;
- (void) setForemanId: (NSString *) foremanId;
#endif
- (BOOL) foremanIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) foremanName;
- (void) setForemanName: (NSString *) foremanName;
#endif
- (BOOL) foremanNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) isDistribute;
- (void) setIsDistribute: (NSString *) isDistribute;
#endif
- (BOOL) isDistributeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) doorTimeShow;
- (void) setDoorTimeShow: (NSString *) doorTimeShow;
#endif
- (BOOL) doorTimeShowIsSet;

#if !__has_feature(objc_arc)
- (NSString *) activitiesName;
- (void) setActivitiesName: (NSString *) activitiesName;
#endif
- (BOOL) activitiesNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) workerName;
- (void) setWorkerName: (NSString *) workerName;
#endif
- (BOOL) workerNameIsSet;

#if !__has_feature(objc_arc)
- (uint8_t) cameraIsBack;
- (void) setCameraIsBack: (uint8_t) cameraIsBack;
#endif
- (BOOL) cameraIsBackIsSet;

#if !__has_feature(objc_arc)
- (NSString *) cameraCode;
- (void) setCameraCode: (NSString *) cameraCode;
#endif
- (BOOL) cameraCodeIsSet;

@end

@interface OrderList : NSObject <TBase, NSCoding> {
  int64_t __total;
  int32_t __currentPage;
  int32_t __pageNumber;
  NSMutableArray * __orders;
  int32_t __type;
  NSString * __searchKey;

  BOOL __total_isset;
  BOOL __currentPage_isset;
  BOOL __pageNumber_isset;
  BOOL __orders_isset;
  BOOL __type_isset;
  BOOL __searchKey_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=total, setter=setTotal:) int64_t total;
@property (nonatomic, getter=currentPage, setter=setCurrentPage:) int32_t currentPage;
@property (nonatomic, getter=pageNumber, setter=setPageNumber:) int32_t pageNumber;
@property (nonatomic, retain, getter=orders, setter=setOrders:) NSMutableArray * orders;
@property (nonatomic, getter=type, setter=setType:) int32_t type;
@property (nonatomic, retain, getter=searchKey, setter=setSearchKey:) NSString * searchKey;
#endif

- (id) init;
- (id) initWithTotal: (int64_t) total currentPage: (int32_t) currentPage pageNumber: (int32_t) pageNumber orders: (NSMutableArray *) orders type: (int32_t) type searchKey: (NSString *) searchKey;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) total;
- (void) setTotal: (int64_t) total;
#endif
- (BOOL) totalIsSet;

#if !__has_feature(objc_arc)
- (int32_t) currentPage;
- (void) setCurrentPage: (int32_t) currentPage;
#endif
- (BOOL) currentPageIsSet;

#if !__has_feature(objc_arc)
- (int32_t) pageNumber;
- (void) setPageNumber: (int32_t) pageNumber;
#endif
- (BOOL) pageNumberIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) orders;
- (void) setOrders: (NSMutableArray *) orders;
#endif
- (BOOL) ordersIsSet;

#if !__has_feature(objc_arc)
- (int32_t) type;
- (void) setType: (int32_t) type;
#endif
- (BOOL) typeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) searchKey;
- (void) setSearchKey: (NSString *) searchKey;
#endif
- (BOOL) searchKeyIsSet;

@end

@interface Notice : NSObject <TBase, NSCoding> {
  int64_t __id;
  int64_t __uid;
  int64_t __orderId;
  NSString * __title;
  NSString * __content;
  uint8_t __status;
  NSString * __createTime;
  NSString * __modifyTime;

  BOOL __id_isset;
  BOOL __uid_isset;
  BOOL __orderId_isset;
  BOOL __title_isset;
  BOOL __content_isset;
  BOOL __status_isset;
  BOOL __createTime_isset;
  BOOL __modifyTime_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int64_t id;
@property (nonatomic, getter=uid, setter=setUid:) int64_t uid;
@property (nonatomic, getter=orderId, setter=setOrderId:) int64_t orderId;
@property (nonatomic, retain, getter=title, setter=setTitle:) NSString * title;
@property (nonatomic, retain, getter=content, setter=setContent:) NSString * content;
@property (nonatomic, getter=status, setter=setStatus:) uint8_t status;
@property (nonatomic, retain, getter=createTime, setter=setCreateTime:) NSString * createTime;
@property (nonatomic, retain, getter=modifyTime, setter=setModifyTime:) NSString * modifyTime;
#endif

- (id) init;
- (id) initWithId: (int64_t) id uid: (int64_t) uid orderId: (int64_t) orderId title: (NSString *) title content: (NSString *) content status: (uint8_t) status createTime: (NSString *) createTime modifyTime: (NSString *) modifyTime;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) id;
- (void) setId: (int64_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (int64_t) uid;
- (void) setUid: (int64_t) uid;
#endif
- (BOOL) uidIsSet;

#if !__has_feature(objc_arc)
- (int64_t) orderId;
- (void) setOrderId: (int64_t) orderId;
#endif
- (BOOL) orderIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) title;
- (void) setTitle: (NSString *) title;
#endif
- (BOOL) titleIsSet;

#if !__has_feature(objc_arc)
- (NSString *) content;
- (void) setContent: (NSString *) content;
#endif
- (BOOL) contentIsSet;

#if !__has_feature(objc_arc)
- (uint8_t) status;
- (void) setStatus: (uint8_t) status;
#endif
- (BOOL) statusIsSet;

#if !__has_feature(objc_arc)
- (NSString *) createTime;
- (void) setCreateTime: (NSString *) createTime;
#endif
- (BOOL) createTimeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) modifyTime;
- (void) setModifyTime: (NSString *) modifyTime;
#endif
- (BOOL) modifyTimeIsSet;

@end

@interface NoticeList : NSObject <TBase, NSCoding> {
  int32_t __total;
  int32_t __currentPage;
  int32_t __pageNumber;
  NSMutableArray * __notices;

  BOOL __total_isset;
  BOOL __currentPage_isset;
  BOOL __pageNumber_isset;
  BOOL __notices_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=total, setter=setTotal:) int32_t total;
@property (nonatomic, getter=currentPage, setter=setCurrentPage:) int32_t currentPage;
@property (nonatomic, getter=pageNumber, setter=setPageNumber:) int32_t pageNumber;
@property (nonatomic, retain, getter=notices, setter=setNotices:) NSMutableArray * notices;
#endif

- (id) init;
- (id) initWithTotal: (int32_t) total currentPage: (int32_t) currentPage pageNumber: (int32_t) pageNumber notices: (NSMutableArray *) notices;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) total;
- (void) setTotal: (int32_t) total;
#endif
- (BOOL) totalIsSet;

#if !__has_feature(objc_arc)
- (int32_t) currentPage;
- (void) setCurrentPage: (int32_t) currentPage;
#endif
- (BOOL) currentPageIsSet;

#if !__has_feature(objc_arc)
- (int32_t) pageNumber;
- (void) setPageNumber: (int32_t) pageNumber;
#endif
- (BOOL) pageNumberIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) notices;
- (void) setNotices: (NSMutableArray *) notices;
#endif
- (BOOL) noticesIsSet;

@end

@interface ServiceItem : NSObject <TBase, NSCoding> {
  int64_t __id;
  NSString * __name;
  NSString * __unit;

  BOOL __id_isset;
  BOOL __name_isset;
  BOOL __unit_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int64_t id;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=unit, setter=setUnit:) NSString * unit;
#endif

- (id) init;
- (id) initWithId: (int64_t) id name: (NSString *) name unit: (NSString *) unit;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) id;
- (void) setId: (int64_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) unit;
- (void) setUnit: (NSString *) unit;
#endif
- (BOOL) unitIsSet;

@end

@interface Material : NSObject <TBase, NSCoding> {
  int64_t __id;
  int32_t __brandId;
  NSString * __name;
  NSString * __unit;

  BOOL __id_isset;
  BOOL __brandId_isset;
  BOOL __name_isset;
  BOOL __unit_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int64_t id;
@property (nonatomic, getter=brandId, setter=setBrandId:) int32_t brandId;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=unit, setter=setUnit:) NSString * unit;
#endif

- (id) init;
- (id) initWithId: (int64_t) id brandId: (int32_t) brandId name: (NSString *) name unit: (NSString *) unit;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) id;
- (void) setId: (int64_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (int32_t) brandId;
- (void) setBrandId: (int32_t) brandId;
#endif
- (BOOL) brandIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) unit;
- (void) setUnit: (NSString *) unit;
#endif
- (BOOL) unitIsSet;

@end

@interface CraftSuit : NSObject <TBase, NSCoding> {
  int64_t __id;
  NSString * __name;

  BOOL __id_isset;
  BOOL __name_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int64_t id;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
#endif

- (id) init;
- (id) initWithId: (int64_t) id name: (NSString *) name;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) id;
- (void) setId: (int64_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

@end

@interface OrderService : NSObject <TBase, NSCoding> {
  int64_t __id;
  int64_t __orderId;
  int64_t __servicePriceId;
  double __area;
  double __fee;
  NSString * __createTime;
  NSString * __modifyTime;
  NSString * __brandName;
  int64_t __brandId;
  NSString * __materialName;
  int64_t __materialId;
  NSString * __serviceItemName;
  int64_t __serviceItemId;
  NSString * __craftSuitName;
  int64_t __craftSuitId;
  NSString * __materialUnit;
  NSString * __unit;

  BOOL __id_isset;
  BOOL __orderId_isset;
  BOOL __servicePriceId_isset;
  BOOL __area_isset;
  BOOL __fee_isset;
  BOOL __createTime_isset;
  BOOL __modifyTime_isset;
  BOOL __brandName_isset;
  BOOL __brandId_isset;
  BOOL __materialName_isset;
  BOOL __materialId_isset;
  BOOL __serviceItemName_isset;
  BOOL __serviceItemId_isset;
  BOOL __craftSuitName_isset;
  BOOL __craftSuitId_isset;
  BOOL __materialUnit_isset;
  BOOL __unit_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int64_t id;
@property (nonatomic, getter=orderId, setter=setOrderId:) int64_t orderId;
@property (nonatomic, getter=servicePriceId, setter=setServicePriceId:) int64_t servicePriceId;
@property (nonatomic, getter=area, setter=setArea:) double area;
@property (nonatomic, getter=fee, setter=setFee:) double fee;
@property (nonatomic, retain, getter=createTime, setter=setCreateTime:) NSString * createTime;
@property (nonatomic, retain, getter=modifyTime, setter=setModifyTime:) NSString * modifyTime;
@property (nonatomic, retain, getter=brandName, setter=setBrandName:) NSString * brandName;
@property (nonatomic, getter=brandId, setter=setBrandId:) int64_t brandId;
@property (nonatomic, retain, getter=materialName, setter=setMaterialName:) NSString * materialName;
@property (nonatomic, getter=materialId, setter=setMaterialId:) int64_t materialId;
@property (nonatomic, retain, getter=serviceItemName, setter=setServiceItemName:) NSString * serviceItemName;
@property (nonatomic, getter=serviceItemId, setter=setServiceItemId:) int64_t serviceItemId;
@property (nonatomic, retain, getter=craftSuitName, setter=setCraftSuitName:) NSString * craftSuitName;
@property (nonatomic, getter=craftSuitId, setter=setCraftSuitId:) int64_t craftSuitId;
@property (nonatomic, retain, getter=materialUnit, setter=setMaterialUnit:) NSString * materialUnit;
@property (nonatomic, retain, getter=unit, setter=setUnit:) NSString * unit;
#endif

- (id) init;
- (id) initWithId: (int64_t) id orderId: (int64_t) orderId servicePriceId: (int64_t) servicePriceId area: (double) area fee: (double) fee createTime: (NSString *) createTime modifyTime: (NSString *) modifyTime brandName: (NSString *) brandName brandId: (int64_t) brandId materialName: (NSString *) materialName materialId: (int64_t) materialId serviceItemName: (NSString *) serviceItemName serviceItemId: (int64_t) serviceItemId craftSuitName: (NSString *) craftSuitName craftSuitId: (int64_t) craftSuitId materialUnit: (NSString *) materialUnit unit: (NSString *) unit;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) id;
- (void) setId: (int64_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (int64_t) orderId;
- (void) setOrderId: (int64_t) orderId;
#endif
- (BOOL) orderIdIsSet;

#if !__has_feature(objc_arc)
- (int64_t) servicePriceId;
- (void) setServicePriceId: (int64_t) servicePriceId;
#endif
- (BOOL) servicePriceIdIsSet;

#if !__has_feature(objc_arc)
- (double) area;
- (void) setArea: (double) area;
#endif
- (BOOL) areaIsSet;

#if !__has_feature(objc_arc)
- (double) fee;
- (void) setFee: (double) fee;
#endif
- (BOOL) feeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) createTime;
- (void) setCreateTime: (NSString *) createTime;
#endif
- (BOOL) createTimeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) modifyTime;
- (void) setModifyTime: (NSString *) modifyTime;
#endif
- (BOOL) modifyTimeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) brandName;
- (void) setBrandName: (NSString *) brandName;
#endif
- (BOOL) brandNameIsSet;

#if !__has_feature(objc_arc)
- (int64_t) brandId;
- (void) setBrandId: (int64_t) brandId;
#endif
- (BOOL) brandIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) materialName;
- (void) setMaterialName: (NSString *) materialName;
#endif
- (BOOL) materialNameIsSet;

#if !__has_feature(objc_arc)
- (int64_t) materialId;
- (void) setMaterialId: (int64_t) materialId;
#endif
- (BOOL) materialIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) serviceItemName;
- (void) setServiceItemName: (NSString *) serviceItemName;
#endif
- (BOOL) serviceItemNameIsSet;

#if !__has_feature(objc_arc)
- (int64_t) serviceItemId;
- (void) setServiceItemId: (int64_t) serviceItemId;
#endif
- (BOOL) serviceItemIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) craftSuitName;
- (void) setCraftSuitName: (NSString *) craftSuitName;
#endif
- (BOOL) craftSuitNameIsSet;

#if !__has_feature(objc_arc)
- (int64_t) craftSuitId;
- (void) setCraftSuitId: (int64_t) craftSuitId;
#endif
- (BOOL) craftSuitIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) materialUnit;
- (void) setMaterialUnit: (NSString *) materialUnit;
#endif
- (BOOL) materialUnitIsSet;

#if !__has_feature(objc_arc)
- (NSString *) unit;
- (void) setUnit: (NSString *) unit;
#endif
- (BOOL) unitIsSet;

@end

@interface OrderPage : NSObject <TBase, NSCoding> {
  int32_t __total;
  int32_t __currentPage;
  int32_t __pageNumber;
  NSMutableDictionary * __orders;
  int32_t __type;
  NSString * __searchKey;

  BOOL __total_isset;
  BOOL __currentPage_isset;
  BOOL __pageNumber_isset;
  BOOL __orders_isset;
  BOOL __type_isset;
  BOOL __searchKey_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=total, setter=setTotal:) int32_t total;
@property (nonatomic, getter=currentPage, setter=setCurrentPage:) int32_t currentPage;
@property (nonatomic, getter=pageNumber, setter=setPageNumber:) int32_t pageNumber;
@property (nonatomic, retain, getter=orders, setter=setOrders:) NSMutableDictionary * orders;
@property (nonatomic, getter=type, setter=setType:) int32_t type;
@property (nonatomic, retain, getter=searchKey, setter=setSearchKey:) NSString * searchKey;
#endif

- (id) init;
- (id) initWithTotal: (int32_t) total currentPage: (int32_t) currentPage pageNumber: (int32_t) pageNumber orders: (NSMutableDictionary *) orders type: (int32_t) type searchKey: (NSString *) searchKey;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) total;
- (void) setTotal: (int32_t) total;
#endif
- (BOOL) totalIsSet;

#if !__has_feature(objc_arc)
- (int32_t) currentPage;
- (void) setCurrentPage: (int32_t) currentPage;
#endif
- (BOOL) currentPageIsSet;

#if !__has_feature(objc_arc)
- (int32_t) pageNumber;
- (void) setPageNumber: (int32_t) pageNumber;
#endif
- (BOOL) pageNumberIsSet;

#if !__has_feature(objc_arc)
- (NSMutableDictionary *) orders;
- (void) setOrders: (NSMutableDictionary *) orders;
#endif
- (BOOL) ordersIsSet;

#if !__has_feature(objc_arc)
- (int32_t) type;
- (void) setType: (int32_t) type;
#endif
- (BOOL) typeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) searchKey;
- (void) setSearchKey: (NSString *) searchKey;
#endif
- (BOOL) searchKeyIsSet;

@end

@interface ActivitiesList : NSObject <TBase, NSCoding> {
  int32_t __id;
  NSString * __name;
  uint8_t __type;

  BOOL __id_isset;
  BOOL __name_isset;
  BOOL __type_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int32_t id;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, getter=type, setter=setType:) uint8_t type;
#endif

- (id) init;
- (id) initWithId: (int32_t) id name: (NSString *) name type: (uint8_t) type;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) id;
- (void) setId: (int32_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (uint8_t) type;
- (void) setType: (uint8_t) type;
#endif
- (BOOL) typeIsSet;

@end

@interface Payment : NSObject <TBase, NSCoding> {
  int32_t __id;
  int64_t __orderId;
  NSString * __paymentNo;
  NSString * __paymentId;
  uint8_t __type;
  double __amount;
  uint8_t __ipay;
  uint8_t __status;
  NSString * __statusName;
  NSString * __remark;
  NSString * __createTime;
  NSString * __modifyTime;

  BOOL __id_isset;
  BOOL __orderId_isset;
  BOOL __paymentNo_isset;
  BOOL __paymentId_isset;
  BOOL __type_isset;
  BOOL __amount_isset;
  BOOL __ipay_isset;
  BOOL __status_isset;
  BOOL __statusName_isset;
  BOOL __remark_isset;
  BOOL __createTime_isset;
  BOOL __modifyTime_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int32_t id;
@property (nonatomic, getter=orderId, setter=setOrderId:) int64_t orderId;
@property (nonatomic, retain, getter=paymentNo, setter=setPaymentNo:) NSString * paymentNo;
@property (nonatomic, retain, getter=paymentId, setter=setPaymentId:) NSString * paymentId;
@property (nonatomic, getter=type, setter=setType:) uint8_t type;
@property (nonatomic, getter=amount, setter=setAmount:) double amount;
@property (nonatomic, getter=ipay, setter=setIpay:) uint8_t ipay;
@property (nonatomic, getter=status, setter=setStatus:) uint8_t status;
@property (nonatomic, retain, getter=statusName, setter=setStatusName:) NSString * statusName;
@property (nonatomic, retain, getter=remark, setter=setRemark:) NSString * remark;
@property (nonatomic, retain, getter=createTime, setter=setCreateTime:) NSString * createTime;
@property (nonatomic, retain, getter=modifyTime, setter=setModifyTime:) NSString * modifyTime;
#endif

- (id) init;
- (id) initWithId: (int32_t) id orderId: (int64_t) orderId paymentNo: (NSString *) paymentNo paymentId: (NSString *) paymentId type: (uint8_t) type amount: (double) amount ipay: (uint8_t) ipay status: (uint8_t) status statusName: (NSString *) statusName remark: (NSString *) remark createTime: (NSString *) createTime modifyTime: (NSString *) modifyTime;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) id;
- (void) setId: (int32_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (int64_t) orderId;
- (void) setOrderId: (int64_t) orderId;
#endif
- (BOOL) orderIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) paymentNo;
- (void) setPaymentNo: (NSString *) paymentNo;
#endif
- (BOOL) paymentNoIsSet;

#if !__has_feature(objc_arc)
- (NSString *) paymentId;
- (void) setPaymentId: (NSString *) paymentId;
#endif
- (BOOL) paymentIdIsSet;

#if !__has_feature(objc_arc)
- (uint8_t) type;
- (void) setType: (uint8_t) type;
#endif
- (BOOL) typeIsSet;

#if !__has_feature(objc_arc)
- (double) amount;
- (void) setAmount: (double) amount;
#endif
- (BOOL) amountIsSet;

#if !__has_feature(objc_arc)
- (uint8_t) ipay;
- (void) setIpay: (uint8_t) ipay;
#endif
- (BOOL) ipayIsSet;

#if !__has_feature(objc_arc)
- (uint8_t) status;
- (void) setStatus: (uint8_t) status;
#endif
- (BOOL) statusIsSet;

#if !__has_feature(objc_arc)
- (NSString *) statusName;
- (void) setStatusName: (NSString *) statusName;
#endif
- (BOOL) statusNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) remark;
- (void) setRemark: (NSString *) remark;
#endif
- (BOOL) remarkIsSet;

#if !__has_feature(objc_arc)
- (NSString *) createTime;
- (void) setCreateTime: (NSString *) createTime;
#endif
- (BOOL) createTimeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) modifyTime;
- (void) setModifyTime: (NSString *) modifyTime;
#endif
- (BOOL) modifyTimeIsSet;

@end

@interface User : NSObject <TBase, NSCoding> {
  int64_t __id;
  NSString * __username;
  NSString * __name;
  NSString * __avatar;
  int64_t __mobilePhone;
  NSString * __storeIds;
  NSString * __email;
  NSString * __emploeId;
  NSString * __aclExtra;
  NSString * __areaIds;
  uint8_t __level;
  int __gender;
  NSString * __age;

  BOOL __id_isset;
  BOOL __username_isset;
  BOOL __name_isset;
  BOOL __avatar_isset;
  BOOL __mobilePhone_isset;
  BOOL __storeIds_isset;
  BOOL __email_isset;
  BOOL __emploeId_isset;
  BOOL __aclExtra_isset;
  BOOL __areaIds_isset;
  BOOL __level_isset;
  BOOL __gender_isset;
  BOOL __age_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int64_t id;
@property (nonatomic, retain, getter=username, setter=setUsername:) NSString * username;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=avatar, setter=setAvatar:) NSString * avatar;
@property (nonatomic, getter=mobilePhone, setter=setMobilePhone:) int64_t mobilePhone;
@property (nonatomic, retain, getter=storeIds, setter=setStoreIds:) NSString * storeIds;
@property (nonatomic, retain, getter=email, setter=setEmail:) NSString * email;
@property (nonatomic, retain, getter=emploeId, setter=setEmploeId:) NSString * emploeId;
@property (nonatomic, retain, getter=aclExtra, setter=setAclExtra:) NSString * aclExtra;
@property (nonatomic, retain, getter=areaIds, setter=setAreaIds:) NSString * areaIds;
@property (nonatomic, getter=level, setter=setLevel:) uint8_t level;
@property (nonatomic, getter=gender, setter=setGender:) int gender;
@property (nonatomic, retain, getter=age, setter=setAge:) NSString * age;
#endif

- (id) init;
- (id) initWithId: (int64_t) id username: (NSString *) username name: (NSString *) name avatar: (NSString *) avatar mobilePhone: (int64_t) mobilePhone storeIds: (NSString *) storeIds email: (NSString *) email emploeId: (NSString *) emploeId aclExtra: (NSString *) aclExtra areaIds: (NSString *) areaIds level: (uint8_t) level gender: (int) gender age: (NSString *) age;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int64_t) id;
- (void) setId: (int64_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) username;
- (void) setUsername: (NSString *) username;
#endif
- (BOOL) usernameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) avatar;
- (void) setAvatar: (NSString *) avatar;
#endif
- (BOOL) avatarIsSet;

#if !__has_feature(objc_arc)
- (int64_t) mobilePhone;
- (void) setMobilePhone: (int64_t) mobilePhone;
#endif
- (BOOL) mobilePhoneIsSet;

#if !__has_feature(objc_arc)
- (NSString *) storeIds;
- (void) setStoreIds: (NSString *) storeIds;
#endif
- (BOOL) storeIdsIsSet;

#if !__has_feature(objc_arc)
- (NSString *) email;
- (void) setEmail: (NSString *) email;
#endif
- (BOOL) emailIsSet;

#if !__has_feature(objc_arc)
- (NSString *) emploeId;
- (void) setEmploeId: (NSString *) emploeId;
#endif
- (BOOL) emploeIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) aclExtra;
- (void) setAclExtra: (NSString *) aclExtra;
#endif
- (BOOL) aclExtraIsSet;

#if !__has_feature(objc_arc)
- (NSString *) areaIds;
- (void) setAreaIds: (NSString *) areaIds;
#endif
- (BOOL) areaIdsIsSet;

#if !__has_feature(objc_arc)
- (uint8_t) level;
- (void) setLevel: (uint8_t) level;
#endif
- (BOOL) levelIsSet;

#if !__has_feature(objc_arc)
- (int) gender;
- (void) setGender: (int) gender;
#endif
- (BOOL) genderIsSet;

#if !__has_feature(objc_arc)
- (NSString *) age;
- (void) setAge: (NSString *) age;
#endif
- (BOOL) ageIsSet;

@end

@interface ResponseMaterialInfo : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  NSString * __msg;
  NSMutableDictionary * __data;

  BOOL __errorCode_isset;
  BOOL __msg_isset;
  BOOL __data_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=msg, setter=setMsg:) NSString * msg;
@property (nonatomic, retain, getter=data, setter=setData:) NSMutableDictionary * data;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode msg: (NSString *) msg data: (NSMutableDictionary *) data;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) msg;
- (void) setMsg: (NSString *) msg;
#endif
- (BOOL) msgIsSet;

#if !__has_feature(objc_arc)
- (NSMutableDictionary *) data;
- (void) setData: (NSMutableDictionary *) data;
#endif
- (BOOL) dataIsSet;

@end

@interface ResponseCraftSuit : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  NSString * __msg;
  NSMutableArray * __data;

  BOOL __errorCode_isset;
  BOOL __msg_isset;
  BOOL __data_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=msg, setter=setMsg:) NSString * msg;
@property (nonatomic, retain, getter=data, setter=setData:) NSMutableArray * data;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode msg: (NSString *) msg data: (NSMutableArray *) data;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) msg;
- (void) setMsg: (NSString *) msg;
#endif
- (BOOL) msgIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) data;
- (void) setData: (NSMutableArray *) data;
#endif
- (BOOL) dataIsSet;

@end

@interface ResponseServiceItem : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  NSString * __msg;
  NSMutableArray * __data;

  BOOL __errorCode_isset;
  BOOL __msg_isset;
  BOOL __data_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=msg, setter=setMsg:) NSString * msg;
@property (nonatomic, retain, getter=data, setter=setData:) NSMutableArray * data;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode msg: (NSString *) msg data: (NSMutableArray *) data;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) msg;
- (void) setMsg: (NSString *) msg;
#endif
- (BOOL) msgIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) data;
- (void) setData: (NSMutableArray *) data;
#endif
- (BOOL) dataIsSet;

@end

@interface ResponseOrderService : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  NSString * __msg;
  NSMutableDictionary * __data;

  BOOL __errorCode_isset;
  BOOL __msg_isset;
  BOOL __data_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=msg, setter=setMsg:) NSString * msg;
@property (nonatomic, retain, getter=data, setter=setData:) NSMutableDictionary * data;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode msg: (NSString *) msg data: (NSMutableDictionary *) data;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) msg;
- (void) setMsg: (NSString *) msg;
#endif
- (BOOL) msgIsSet;

#if !__has_feature(objc_arc)
- (NSMutableDictionary *) data;
- (void) setData: (NSMutableDictionary *) data;
#endif
- (BOOL) dataIsSet;

@end

@interface ResponseOrder : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  NSString * __msg;
  Order * __data;

  BOOL __errorCode_isset;
  BOOL __msg_isset;
  BOOL __data_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=msg, setter=setMsg:) NSString * msg;
@property (nonatomic, retain, getter=data, setter=setData:) Order * data;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode msg: (NSString *) msg data: (Order *) data;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) msg;
- (void) setMsg: (NSString *) msg;
#endif
- (BOOL) msgIsSet;

#if !__has_feature(objc_arc)
- (Order *) data;
- (void) setData: (Order *) data;
#endif
- (BOOL) dataIsSet;

@end

@interface ResponseOrderList : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  NSString * __msg;
  OrderPage * __data;

  BOOL __errorCode_isset;
  BOOL __msg_isset;
  BOOL __data_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=msg, setter=setMsg:) NSString * msg;
@property (nonatomic, retain, getter=data, setter=setData:) OrderPage * data;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode msg: (NSString *) msg data: (OrderPage *) data;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) msg;
- (void) setMsg: (NSString *) msg;
#endif
- (BOOL) msgIsSet;

#if !__has_feature(objc_arc)
- (OrderPage *) data;
- (void) setData: (OrderPage *) data;
#endif
- (BOOL) dataIsSet;

@end

@interface ResponseActivities : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  NSString * __msg;
  NSMutableDictionary * __data;

  BOOL __errorCode_isset;
  BOOL __msg_isset;
  BOOL __data_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=msg, setter=setMsg:) NSString * msg;
@property (nonatomic, retain, getter=data, setter=setData:) NSMutableDictionary * data;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode msg: (NSString *) msg data: (NSMutableDictionary *) data;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) msg;
- (void) setMsg: (NSString *) msg;
#endif
- (BOOL) msgIsSet;

#if !__has_feature(objc_arc)
- (NSMutableDictionary *) data;
- (void) setData: (NSMutableDictionary *) data;
#endif
- (BOOL) dataIsSet;

@end

@interface ResponseNoticeList : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  NSString * __msg;
  NoticeList * __data;

  BOOL __errorCode_isset;
  BOOL __msg_isset;
  BOOL __data_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=msg, setter=setMsg:) NSString * msg;
@property (nonatomic, retain, getter=data, setter=setData:) NoticeList * data;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode msg: (NSString *) msg data: (NoticeList *) data;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) msg;
- (void) setMsg: (NSString *) msg;
#endif
- (BOOL) msgIsSet;

#if !__has_feature(objc_arc)
- (NoticeList *) data;
- (void) setData: (NoticeList *) data;
#endif
- (BOOL) dataIsSet;

@end

@interface AUser : NSObject <TBase, NSCoding> {
  int32_t __uid;
  NSString * __name;

  BOOL __uid_isset;
  BOOL __name_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=uid, setter=setUid:) int32_t uid;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
#endif

- (id) init;
- (id) initWithUid: (int32_t) uid name: (NSString *) name;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) uid;
- (void) setUid: (int32_t) uid;
#endif
- (BOOL) uidIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

@end

@interface ResponseUserList : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  NSString * __msg;
  NSMutableArray * __data;

  BOOL __errorCode_isset;
  BOOL __msg_isset;
  BOOL __data_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=msg, setter=setMsg:) NSString * msg;
@property (nonatomic, retain, getter=data, setter=setData:) NSMutableArray * data;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode msg: (NSString *) msg data: (NSMutableArray *) data;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) msg;
- (void) setMsg: (NSString *) msg;
#endif
- (BOOL) msgIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) data;
- (void) setData: (NSMutableArray *) data;
#endif
- (BOOL) dataIsSet;

@end

@interface ResponsePaymentList : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  NSString * __msg;
  NSMutableArray * __data;

  BOOL __errorCode_isset;
  BOOL __msg_isset;
  BOOL __data_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=msg, setter=setMsg:) NSString * msg;
@property (nonatomic, retain, getter=data, setter=setData:) NSMutableArray * data;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode msg: (NSString *) msg data: (NSMutableArray *) data;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) msg;
- (void) setMsg: (NSString *) msg;
#endif
- (BOOL) msgIsSet;

#if !__has_feature(objc_arc)
- (NSMutableArray *) data;
- (void) setData: (NSMutableArray *) data;
#endif
- (BOOL) dataIsSet;

@end

@interface ResponseUserInfo : NSObject <TBase, NSCoding> {
  int32_t __errorCode;
  NSString * __msg;
  User * __data;

  BOOL __errorCode_isset;
  BOOL __msg_isset;
  BOOL __data_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=msg, setter=setMsg:) NSString * msg;
@property (nonatomic, retain, getter=data, setter=setData:) User * data;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode msg: (NSString *) msg data: (User *) data;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) msg;
- (void) setMsg: (NSString *) msg;
#endif
- (BOOL) msgIsSet;

#if !__has_feature(objc_arc)
- (User *) data;
- (void) setData: (User *) data;
#endif
- (BOOL) dataIsSet;

@end

@protocol IpadPSR <NSObject>
- (Response *) getVerificationCode: (Auth *) auth mobile: (NSString *) mobile;  // throws InvalidOperation *, TException
- (ResponseAuth *) login: (Auth *) auth mobile: (NSString *) mobile verificationCode: (NSString *) verificationCode deviceToken: (NSString *) deviceToken;  // throws InvalidOperation *, TException
- (Response *) logout: (Auth *) auth mobile: (NSString *) mobile;  // throws InvalidOperation *, TException
- (ResponseOrderList *) getOrderList: (Auth *) auth type: (uint8_t) type page: (int32_t) page size: (int32_t) size searchKey: (NSString *) searchKey;  // throws InvalidOperation *, TException
- (ResponseOrder *) getOrderInfoByOrderId: (Auth *) auth orderId: (int64_t) orderId;  // throws InvalidOperation *, TException
- (ResponseOrderService *) getOrderMeasureByOrderId: (Auth *) auth orderId: (int64_t) orderId;  // throws InvalidOperation *, TException
- (Response *) setOrderDoorTime: (Auth *) auth orderId: (int64_t) orderId doorTime: (NSString *) doorTime remark: (NSString *) remark;  // throws InvalidOperation *, TException
- (Response *) psrStopOrder: (Auth *) auth orderId: (int64_t) orderId pauseReasonMemo: (NSString *) pauseReasonMemo remark: (NSString *) remark;  // throws InvalidOperation *, TException
- (ResponseUserList *) getForeman: (Auth *) auth orderId: (int64_t) orderId startTime: (NSString *) startTime endTime: (NSString *) endTime longitude: (double) longitude latitude: (double) latitude;  // throws InvalidOperation *, TException
- (Response *) setForeman: (Auth *) auth orderId: (int64_t) orderId startTime: (NSString *) startTime endTime: (NSString *) endTime uid: (int32_t) uid remark: (NSString *) remark;  // throws InvalidOperation *, TException
- (Response *) uploadOrderPhoto: (Auth *) auth orderId: (int64_t) orderId type: (uint8_t) type photo: (NSData *) photo ext: (NSString *) ext;  // throws InvalidOperation *, TException
- (Response *) deleteOrderPhoto: (Auth *) auth orderId: (int64_t) orderId type: (uint8_t) type filename: (NSMutableArray *) filename;  // throws InvalidOperation *, TException
- (Response *) finishOrder: (Auth *) auth orderId: (int64_t) orderId;  // throws InvalidOperation *, TException
- (Response *) bindCamera: (Auth *) auth orderId: (int64_t) orderId cameraCode: (NSString *) cameraCode;  // throws InvalidOperation *, TException
- (Response *) getCameraUrl: (Auth *) auth orderId: (int64_t) orderId;  // throws InvalidOperation *, TException
- (ResponseNoticeList *) getNoticeList: (Auth *) auth page: (int32_t) page pageNumber: (int32_t) pageNumber;  // throws InvalidOperation *, TException
- (Response *) setNoticeHaveRead: (Auth *) auth noticeId: (int64_t) noticeId;  // throws InvalidOperation *, TException
- (ResponseServiceItem *) getServiceListForOptool: (Auth *) auth serviceItemId: (NSMutableArray *) serviceItemId;  // throws InvalidOperation *, TException
- (ResponseCraftSuit *) getCraftSuitByServiceItemId: (Auth *) auth serviceItemId: (int64_t) serviceItemId;  // throws InvalidOperation *, TException
- (ResponseMaterialInfo *) getMaterialInfoByCond: (Auth *) auth serviceItemId: (int64_t) serviceItemId craftSuitId: (int64_t) craftSuitId;  // throws InvalidOperation *, TException
- (ResponseDouble *) getPriceByCond: (Auth *) auth serviceItemId: (int64_t) serviceItemId craftSuitId: (int64_t) craftSuitId materialId: (int64_t) materialId;  // throws InvalidOperation *, TException
- (Response *) saveOrderService: (Auth *) auth orderId: (int64_t) orderId mobilePhone: (int64_t) mobilePhone userCalled: (NSString *) userCalled address: (NSString *) address services: (NSMutableArray *) services;  // throws InvalidOperation *, TException
- (Response *) followsOrder: (Auth *) auth orderId: (int64_t) orderId remark: (NSString *) remark;  // throws TException
- (Response *) checkIsDeleteErpOrder: (Auth *) auth orderId: (int64_t) orderId;  // throws TException
- (ResponseActivities *) getActivitiesList: (Auth *) auth orderId: (int64_t) orderId;  // throws TException
- (ResponseDouble *) checkCoupon: (Auth *) auth orderId: (int64_t) orderId couponCardNo: (NSString *) couponCardNo activitiesId: (int64_t) activitiesId;  // throws TException
- (Response *) saveOrderActivities: (Auth *) auth orderId: (int64_t) orderId remark: (NSString *) remark camera: (uint8_t) camera couponCardNo: (NSString *) couponCardNo activitiesId: (int32_t) activitiesId num: (int32_t) num longitude: (double) longitude latitude: (double) latitude;  // throws TException
- (ResponsePaymentList *) getPaymentInfoByOrderId: (Auth *) auth orderId: (int64_t) orderId;  // throws TException
- (ResponseUserInfo *) getUserInfoByUid: (Auth *) auth uid: (int64_t) uid;  // throws InvalidOperation *, TException
@end

@interface IpadPSRClient : TBaseClient <IpadPSR> - (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface IpadPSRProcessor : NSObject <TProcessor> {
  id <IpadPSR> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithIpadPSR: (id <IpadPSR>) service;
- (id<IpadPSR>) service;
@end

@interface IpadPSRConstants : NSObject {
}
@end
